package primero;
// Generated 06-may-2018 17:11:48 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Articulos generated by hbm2java
 */
public class Articulos implements java.io.Serializable {

	private ArticulosId id;
	private Fabricantes fabricantes;
	private Float precioVenta;
	private Float precioCosto;
	private Short existencias;
	private Set<Ventas> ventases = new HashSet<Ventas>(0);
	private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);

	public Articulos() {
	}

	public Articulos(ArticulosId id, Fabricantes fabricantes) {
		this.id = id;
		this.fabricantes = fabricantes;
	}

	public Articulos(ArticulosId id, Fabricantes fabricantes, Float precioVenta, Float precioCosto, Short existencias,
			Set<Ventas> ventases, Set<Pedidos> pedidoses) {
		this.id = id;
		this.fabricantes = fabricantes;
		this.precioVenta = precioVenta;
		this.precioCosto = precioCosto;
		this.existencias = existencias;
		this.ventases = ventases;
		this.pedidoses = pedidoses;
	}

	public ArticulosId getId() {
		return this.id;
	}

	public void setId(ArticulosId id) {
		this.id = id;
	}

	public Fabricantes getFabricantes() {
		return this.fabricantes;
	}

	public void setFabricantes(Fabricantes fabricantes) {
		this.fabricantes = fabricantes;
	}

	public Float getPrecioVenta() {
		return this.precioVenta;
	}

	public void setPrecioVenta(Float precioVenta) {
		this.precioVenta = precioVenta;
	}

	public Float getPrecioCosto() {
		return this.precioCosto;
	}

	public void setPrecioCosto(Float precioCosto) {
		this.precioCosto = precioCosto;
	}

	public Short getExistencias() {
		return this.existencias;
	}

	public void setExistencias(Short existencias) {
		this.existencias = existencias;
	}

	public Set<Ventas> getVentases() {
		return this.ventases;
	}

	public void setVentases(Set<Ventas> ventases) {
		this.ventases = ventases;
	}

	public Set<Pedidos> getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set<Pedidos> pedidoses) {
		this.pedidoses = pedidoses;
	}

	@Override
	public String toString() {
		return "ARTICULO: " + getId().getArticulo() + "  " + "FABRICANTE: " + getFabricantes().getNombre();
	}

	
	
}
