package primero;
// Generated 06-may-2018 17:11:48 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Fabricantes generated by hbm2java
 */
public class Fabricantes implements java.io.Serializable {

	private short codFabricante;
	private String nombre;
	private String pais;
	private Set<Articulos> articuloses = new HashSet<Articulos>(0);

	public Fabricantes() {
	}

	public Fabricantes(short codFabricante) {
		this.codFabricante = codFabricante;
	}

	public Fabricantes(short codFabricante, String nombre, String pais, Set<Articulos> articuloses) {
		this.codFabricante = codFabricante;
		this.nombre = nombre;
		this.pais = pais;
		this.articuloses = articuloses;
	}

	public short getCodFabricante() {
		return this.codFabricante;
	}

	public void setCodFabricante(short codFabricante) {
		this.codFabricante = codFabricante;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public Set<Articulos> getArticuloses() {
		return this.articuloses;
	}

	public void setArticuloses(Set<Articulos> articuloses) {
		this.articuloses = articuloses;
	}

}
