package primero;
// Generated 06-may-2018 17:11:48 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * PedidosId generated by hbm2java
 */
public class PedidosId implements java.io.Serializable {

	private String nif;
	private String articulo;
	private short codFabricante;
	private short peso;
	private String categoria;
	private Date fechaPedido;

	public PedidosId() {
	}

	public PedidosId(String nif, String articulo, short codFabricante, short peso, String categoria, Date fechaPedido) {
		this.nif = nif;
		this.articulo = articulo;
		this.codFabricante = codFabricante;
		this.peso = peso;
		this.categoria = categoria;
		this.fechaPedido = fechaPedido;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getArticulo() {
		return this.articulo;
	}

	public void setArticulo(String articulo) {
		this.articulo = articulo;
	}

	public short getCodFabricante() {
		return this.codFabricante;
	}

	public void setCodFabricante(short codFabricante) {
		this.codFabricante = codFabricante;
	}

	public short getPeso() {
		return this.peso;
	}

	public void setPeso(short peso) {
		this.peso = peso;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PedidosId))
			return false;
		PedidosId castOther = (PedidosId) other;

		return ((this.getNif() == castOther.getNif())
				|| (this.getNif() != null && castOther.getNif() != null && this.getNif().equals(castOther.getNif())))
				&& ((this.getArticulo() == castOther.getArticulo()) || (this.getArticulo() != null
						&& castOther.getArticulo() != null && this.getArticulo().equals(castOther.getArticulo())))
				&& (this.getCodFabricante() == castOther.getCodFabricante()) && (this.getPeso() == castOther.getPeso())
				&& ((this.getCategoria() == castOther.getCategoria()) || (this.getCategoria() != null
						&& castOther.getCategoria() != null && this.getCategoria().equals(castOther.getCategoria())))
				&& ((this.getFechaPedido() == castOther.getFechaPedido())
						|| (this.getFechaPedido() != null && castOther.getFechaPedido() != null
								&& this.getFechaPedido().equals(castOther.getFechaPedido())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNif() == null ? 0 : this.getNif().hashCode());
		result = 37 * result + (getArticulo() == null ? 0 : this.getArticulo().hashCode());
		result = 37 * result + this.getCodFabricante();
		result = 37 * result + this.getPeso();
		result = 37 * result + (getCategoria() == null ? 0 : this.getCategoria().hashCode());
		result = 37 * result + (getFechaPedido() == null ? 0 : this.getFechaPedido().hashCode());
		return result;
	}

}
