package primero;
// Generated 06-may-2018 17:11:48 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * VentasId generated by hbm2java
 */
public class VentasId implements java.io.Serializable {

	private String nif;
	private String articulo;
	private short codFabricante;
	private short peso;
	private String categoria;
	private Date fechaVenta;

	public VentasId() {
	}

	public VentasId(String nif, String articulo, short codFabricante, short peso, String categoria, Date fechaVenta) {
		this.nif = nif;
		this.articulo = articulo;
		this.codFabricante = codFabricante;
		this.peso = peso;
		this.categoria = categoria;
		this.fechaVenta = fechaVenta;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getArticulo() {
		return this.articulo;
	}

	public void setArticulo(String articulo) {
		this.articulo = articulo;
	}

	public short getCodFabricante() {
		return this.codFabricante;
	}

	public void setCodFabricante(short codFabricante) {
		this.codFabricante = codFabricante;
	}

	public short getPeso() {
		return this.peso;
	}

	public void setPeso(short peso) {
		this.peso = peso;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public Date getFechaVenta() {
		return this.fechaVenta;
	}

	public void setFechaVenta(Date fechaVenta) {
		this.fechaVenta = fechaVenta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VentasId))
			return false;
		VentasId castOther = (VentasId) other;

		return ((this.getNif() == castOther.getNif())
				|| (this.getNif() != null && castOther.getNif() != null && this.getNif().equals(castOther.getNif())))
				&& ((this.getArticulo() == castOther.getArticulo()) || (this.getArticulo() != null
						&& castOther.getArticulo() != null && this.getArticulo().equals(castOther.getArticulo())))
				&& (this.getCodFabricante() == castOther.getCodFabricante()) && (this.getPeso() == castOther.getPeso())
				&& ((this.getCategoria() == castOther.getCategoria()) || (this.getCategoria() != null
						&& castOther.getCategoria() != null && this.getCategoria().equals(castOther.getCategoria())))
				&& ((this.getFechaVenta() == castOther.getFechaVenta())
						|| (this.getFechaVenta() != null && castOther.getFechaVenta() != null
								&& this.getFechaVenta().equals(castOther.getFechaVenta())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNif() == null ? 0 : this.getNif().hashCode());
		result = 37 * result + (getArticulo() == null ? 0 : this.getArticulo().hashCode());
		result = 37 * result + this.getCodFabricante();
		result = 37 * result + this.getPeso();
		result = 37 * result + (getCategoria() == null ? 0 : this.getCategoria().hashCode());
		result = 37 * result + (getFechaVenta() == null ? 0 : this.getFechaVenta().hashCode());
		return result;
	}

}
