package primero;
// Generated 06-may-2018 17:11:48 by Hibernate Tools 3.5.0.Final

/**
 * Ventas generated by hbm2java
 */
public class Ventas implements java.io.Serializable {

	private VentasId id;
	private Tiendas tiendas;
	private Articulos articulos;
	private Short unidadesVendidas;

	public Ventas() {
	}

	public Ventas(VentasId id, Tiendas tiendas, Articulos articulos) {
		this.id = id;
		this.tiendas = tiendas;
		this.articulos = articulos;
	}

	public Ventas(VentasId id, Tiendas tiendas, Articulos articulos, Short unidadesVendidas) {
		this.id = id;
		this.tiendas = tiendas;
		this.articulos = articulos;
		this.unidadesVendidas = unidadesVendidas;
	}

	public VentasId getId() {
		return this.id;
	}

	public void setId(VentasId id) {
		this.id = id;
	}

	public Tiendas getTiendas() {
		return this.tiendas;
	}

	public void setTiendas(Tiendas tiendas) {
		this.tiendas = tiendas;
	}

	public Articulos getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Articulos articulos) {
		this.articulos = articulos;
	}

	public Short getUnidadesVendidas() {
		return this.unidadesVendidas;
	}

	public void setUnidadesVendidas(Short unidadesVendidas) {
		this.unidadesVendidas = unidadesVendidas;
	}

	@Override
	public String toString() {
		return "Ventas [id=" + id + ", tiendas=" + tiendas + ", articulos=" + articulos + ", unidadesVendidas="
				+ unidadesVendidas + "]";
	}
	
	

}
